export const courses = [
  {
    title: "Advanced Mathematics",
    category: "Science",
    students: 1240,
    rating: 4.8,
    reviews: 1100,
    videos: 32,
    price: 140,
    discountPercent: 50,
    badge: "Best seller",
    image:
      "https://images.pexels.com/photos/3729557/pexels-photo-3729557.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "English Language & Literature",
    category: "Arts",
    students: 980,
    rating: 4.7,
    reviews: 860,
    videos: 24,
    price: 110,
    discountPercent: 40,
    badge: "Top rated",
    image:
      "https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Biology & Life Sciences",
    category: "Science",
    students: 1560,
    rating: 4.9,
    reviews: 1420,
    videos: 40,
    price: 160,
    discountPercent: 50,
    badge: "Best reviewed",
    image:
      "https://images.pexels.com/photos/3825539/pexels-photo-3825539.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Physics Fundamentals",
    category: "Science",
    students: 870,
    rating: 4.6,
    reviews: 740,
    videos: 28,
    price: 130,
    discountPercent: 35,
    badge: "New",
    image:
      "https://images.pexels.com/photos/2280549/pexels-photo-2280549.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Economics & Commerce",
    category: "Social Sci.",
    students: 1100,
    rating: 4.5,
    reviews: 940,
    videos: 30,
    price: 120,
    discountPercent: 45,
    badge: "Trending",
    image:
      "https://images.pexels.com/photos/730547/pexels-photo-730547.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Chemistry in Depth",
    category: "Science",
    students: 1320,
    rating: 4.8,
    reviews: 1180,
    videos: 36,
    price: 150,
    discountPercent: 50,
    badge: "Best mentor",
    image:
      "https://images.pexels.com/photos/2280571/pexels-photo-2280571.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];
