"use client";

import { BookOpen, FileX } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import "./tiptapStyles.css";
import "katex/dist/katex.min.css";
import parse from "html-react-parser";
import { InlineMath, BlockMath } from "react-katex";

interface RichContentViewerProps {
  content: string;
}

export function RichContentViewer({ content }: RichContentViewerProps) {
  if (!content || content.trim().length === 0) {
    return (
      <Card className="overflow-hidden border-border/70 bg-card shadow-sm">
        <CardHeader className="border-b border-border/50 bg-muted/20  py-4 sm:px-6">
          <CardTitle className="flex items-center gap-2 text-base font-bold">
            <BookOpen className="h-5 w-5 text-primary" />
            Study Content
          </CardTitle>
        </CardHeader>

        <CardContent>
          <div className="flex flex-col items-center justify-center gap-4 py-16 text-center sm:py-20">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-muted">
              <FileX className="h-8 w-8 text-muted-foreground" />
            </div>

            <div className="max-w-sm">
              <p className="text-sm font-semibold text-foreground">
                Content for this topic has not been added yet.
              </p>

              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
                Please check back later.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="overflow-hidden border-border/70 bg-card shadow-sm ">
      {/* Header */}
      <CardHeader className="border-b border-border/50 bg-muted/10 px-4 py-4 sm:px-6">
        <CardTitle className="flex items-center gap-2 text-base font-bold">
          <BookOpen className="h-5 w-5 text-primary" />
          Study Content
        </CardTitle>
      </CardHeader>

      {/* Reading area */}
      <CardContent className="p-0">
        <article className="study-reading-shell">
          <div className="tiptap-content study-reading-content">
            {parse(content, {
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              replace(domNode: any) {
                /*
                 * Block math generated by Tiptap
                 */
                if (
                  domNode.name === "div" &&
                  domNode.attribs?.["data-type"] === "block-math"
                ) {
                  const latex = domNode.attribs?.["data-latex"] ?? "";

                  return (
                    <div className="study-block-math">
                      <BlockMath math={latex} />
                    </div>
                  );
                }

                /*
                 * Inline math generated by Tiptap
                 */
                if (
                  domNode.name === "span" &&
                  domNode.attribs?.["data-type"] === "inline-math"
                ) {
                  const latex = domNode.attribs?.["data-latex"] ?? "";

                  return <InlineMath math={latex} />;
                }

                return undefined;
              },
            })}
          </div>
        </article>
      </CardContent>
    </Card>
  );
}
